MerxProject/Models/Producto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MerxProject.Models
{
    public class Producto
    {
        public int Id { get; set; }
        [Required]
        public string Nombre { get; set; }
        [Required]
        public string Descripcion { get; set; }
        [Required]
        public string Imagen { get; set; }

        [Required]
        public Mueble CategoriaMueble { get; set; }
        [Required]
        public Material CategoriaMaterial { get; set; }

        [Required]
        public float Precio { get; set; }

        [Required]
        public int Cantidad { get; set; }
    }
}

MerxProject/Models/TiendaViewModels/TiendaViewModel.cs
using MerxProject.Models.ProductosFavorito;
using MerxProject.Models.CarritoCompras;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MerxProject.Models.TiendaViewModels
{
    public class TiendaViewModel
    {
        public Producto Producto { get; set; }

        public List<Producto> ProductoCollection { get; set; }

        public ProductosFavoritos ProductosFavorito { get; set; }

        public List<ProductosFavoritos> ProductosFavoritosColelction { get; set; }
        public List<CarritoCompra> ProductosCarritoCollection { get; set; }

        public CarritoCompra CarritoCompra { get; set; }

        public List<int> ProductosFavId { get; set; }
        public List<int> ProductosCarrito { get; set; }

    }
}

MerxProject/Controllers/ProductoController.cs
using MerxProject.Models;
using MerxProject.Models.ProductosFavorito;
using MerxProject.Models.CarritoCompras;
using MerxProject.Models.TiendaViewModels;
using MerxProject.Models.VentaViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.IO;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace MerxProject.Controllers
{

    public class ProductoController : Controller
    {
        private readonly int _RegistrosPorPagina = 10;

        private List<Inventario> _Productos;
        private PaginadorGenerico<Inventario> _PaginadorProductos;
        private List<Producto> _Producto;
        private PaginadorGenerico<Producto> _PaginadorProducto;

        // GET: Producto
        //public ActionResult Tienda(int pagina = 1)

        ApplicationDbContext DbModel;


        public ProductoController()
        {
            this.DbModel = new ApplicationDbContext();
        }

        // GET: Producto
        [AllowAnonymous]
        [HttpGet]
        public ActionResult Tienda(int? NoLogIn, int? OutStock, string colorNombre = null, int pag = 1)
        {
            if (pag <= 0) pag = 1;

            if (OutStock != null)
            {
                ViewBag.outStock = 1;
                ViewBag.nombreColor = colorNombre;
            }
            else
            {
                ViewBag.outStock = 0;
            }

            var email = User.Identity.Name;

            if (email != "" && email.Contains("@"))
            {
                ViewBag.NoLogIn = 1;
                var usuarioLoggeado = DbModel.Personas.FirstOrDefault(x => x.Correo == email);


                TiendaViewModel tiendaViewModel = new TiendaViewModel();
                tiendaViewModel.ProductoCollection = DbModel.Productos.ToList();

                tiendaViewModel.ProductosFavoritosColelction = DbModel.ProductosFavoritos.Where(x => x.idPersona == usuarioLoggeado.idPersona).OrderBy(x => x.idProducto).ToList();
                tiendaViewModel.ProductosCarritoCollection = DbModel.CarritoCompras.Where(x => x.idPersona == usuarioLoggeado.idPersona).OrderBy(x => x.idProducto).ToList();

                tiendaViewModel.ProductosFavId = new List<int>();
                tiendaViewModel.ProductosCarrito = new List<int>();

                int idxAux = 0;
                foreach (var item in tiendaViewModel.ProductoCollection)
                {
                    if (idxAux < tiendaViewModel.ProductosFavoritosColelction.Count)
                    {
                        if (item.Id == tiendaViewModel.ProductosFavoritosColelction[idxAux].idProducto)
                        {
                            tiendaViewModel.ProductosFavId.Add(item.Id);

                            idxAux++;
                        }
                        else
                        {

                            tiendaViewModel.ProductosFavId.Add(-1);
                        }
                    }
                    else
                    {
                        tiendaViewModel.ProductosFavId.Add(-1);
                    }

                }
                int idxAux2 = 0;

                foreach (var item in tiendaViewModel.ProductoCollection)
                {
                    if (idxAux2 < tiendaViewModel.ProductosCarritoCollection.Count)
                    {
                        if (item.Id == tiendaViewModel.ProductosCarritoCollection[idxAux2].idProducto)
                        {
                            tiendaViewModel.ProductosCarrito.Add(item.Id);

                            idxAux2++;
                        }
                        else
                        {

                            tiendaViewModel.ProductosCarrito.Add(-1);
                        }
                    }
                    else
                    {
                        tiendaViewModel.ProductosCarrito.Add(-1);
                    }

                }
                ViewBag.pagina = pag;
                return View(tiendaViewModel);
            }
            else
            {
                ViewBag.NoLogIn = 0;
                TiendaViewModel tiendaViewModel = new TiendaViewModel();
                tiendaViewModel.ProductoCollection = DbModel.Productos.ToList();
                ViewBag.pagina = pag;
                return View(tiendaViewModel);
            }
        }

        [HttpPost]
        public ActionResult Tienda()
        {
            return View();
        }


        public ActionResult MostrarTodos(int pagina = 1)
        {
            int _TotalRegistros = 0;
            using (ApplicationDbContext DbModel = new ApplicationDbContext())
            {
                // Número total de registros de la tabla Productos
                _TotalRegistros = DbModel.Productos.Count();
                // Obtenemos la 'página de registros' de la tabla Productos
                _Productos = DbModel.Inventarios.Where(x => x.Cantidad > 0)
                                                 .OrderBy(x => x.Producto.Nombre)
                                                 .Skip((pagina - 1) * _RegistrosPorPagina)
                                                 .Take(_RegistrosPorPagina)
                                                 .ToList();
                // Número total de páginas de la tabla Productos
                var _TotalPaginas = (int)Math.Ceiling((double)_TotalRegistros / _RegistrosPorPagina);
                // Instanciamos la 'Clase de paginación' y asignamos los nuevos valores
                _PaginadorProductos = new PaginadorGenerico<Inventario>()
                {
                    RegistrosPorPagina = _RegistrosPorPagina,
                    TotalRegistros = _TotalRegistros,
                    TotalPaginas = _TotalPaginas,
                    PaginaActual = pagina,
                    Resultado = _Productos
                };
                // Enviamos a la Vista la 'Clase de paginación'
                return View(_PaginadorProductos);
            }
        }

        public ActionResult VistaProducto(int? id)
        {
            using (ApplicationDbContext DbModel = new ApplicationDbContext())
            {
                var Materiales = DbModel.Materiales.ToList();
                var Muebles = DbModel.Muebles.ToList();
                ViewBag.Materiales = Materiales;
                ViewBag.Muebles = Muebles;
                //Obtiene el producto que coincida con el ID seleccionado de la lista MostrarTodos(). 
                var producto = DbModel.Inventarios.Find(id);
                return View(producto);
            }
        }

        public ActionResult Buscar(string parameter, int pagina = 1)
        {
            int _TotalRegistros = 0;
            using (ApplicationDbContext DbModel = new ApplicationDbContext())
            {
                var Materiales = DbModel.Materiales.ToList();
                var Muebles = DbModel.Muebles.ToList();
                ViewBag.Materiales = Materiales;
                ViewBag.Muebles = Muebles;

                // Número total de registros de la tabla Productos donde sean parecidos al parámetro
                _TotalRegistros = DbModel.Inventarios.Where(x => x.Producto.Nombre.Contains(parameter) ||
                    (x.Producto.Descripcion.Contains(parameter)) ||
                    (x.Color.Nombre.Contains(parameter)) ||
                    (x.Producto.CategoriaMaterial.Nombre.Contains(parameter)) ||
                    (x.Producto.CategoriaMueble.Nombre.Contains(parameter)) ||
                    (x.Producto.Precio.ToString().Contains(parameter))).Count();
                // Obtenemos la 'página de registros' de la tabla Productos donde sean parecidos al parámetro
                _Productos = DbModel.Inventarios.Where(x => x.Producto.Nombre.Contains(parameter) ||
                    (x.Producto.Descripcion.Contains(parameter)) ||
                    (x.Color.Nombre.Contains(parameter)) ||
                    (x.Producto.CategoriaMaterial.Nombre.Contains(parameter)) ||
                    (x.Producto.CategoriaMueble.Nombre.Contains(parameter)) ||
                    (x.Producto.Precio.ToString().Contains(parameter))).OrderBy(x => x.Producto.Nombre)
                                                 .Skip((pagina - 1) * _RegistrosPorPagina)
                                                 .Take(_RegistrosPorPagina)
                                                 .ToList();
                // Número total de páginas de la tabla Productos donde sean parecidos al parámetro
                var _TotalPaginas = (int)Math.Ceiling((double)_TotalRegistros / _RegistrosPorPagina);
                // Instanciamos la 'Clase de paginación' y asignamos los nuevos valores
                _PaginadorProductos = new PaginadorGenerico<Inventario>()
                {
                    RegistrosPorPagina = _RegistrosPorPagina,
                    TotalRegistros = _TotalRegistros,
                    TotalPaginas = _TotalPaginas,
                    PaginaActual = pagina,
                    Resultado = _Productos
                };

                if (_TotalRegistros < 1)
                {
                    ViewBag.alert = ("No hay resultados");
                    return View("Tienda");
                }
                else
                {
                    return View(_PaginadorProductos);
                }
            }
        }

        [HttpGet]
        public ActionResult popUpProductos(int? Id, string accion)
        {
            using (ApplicationDbContext DbModel = new ApplicationDbContext())
            {
                var Materiales = DbModel.Materiales.Where(x => x.Piezas == true).ToList();
                var Muebles = DbModel.Muebles.ToList();
                ViewBag.Materiales = Materiales;
                ViewBag.Muebles = Muebles;
                if (accion == "1")
                {
                    ViewBag.title = "Nuevo";

MerxProject/Views/Producto/Buscar.cshtml
@model MerxProject.Models.PaginadorGenerico<MerxProject.Models.Producto>


@{
    ViewBag.Title = "Tienda Virtual";
    Layout = "~/Views/Shared/_LayoutTienda.cshtml";
}
<title>Muebleria Merx - Tienda Virtual</title>
<!-- Custom styles for this template -->
<link href="~/Content/assets/vendor/bootstrap/css/shop-homepage.css" rel="stylesheet">

<!-- ======= Hero Section ======= -->
<section id="hero-store" class="d-flex align-items-center justify-content-center">
    <div class="container text-center position-relative align-content-center justify-content-center " data-aos="fade-in" data-aos-delay="200">
        <div class="container text-center position-relative" data-aos="fade-in" data-aos-delay="200">
            <h1>Tienda Merx</h1>
        </div>
    </div>
</section><!-- End Hero -->
<!-- ======= Clients Section ======= -->
<section id="" class="clients">
    <div class="container">
        <div class="row">
            <div class="breadcrumb">
                <a href="@Url.Action("Index", "Home")" class="breadcrumb-item">Inicio</a>
                <a href="#" class="breadcrumb-item">Tienda Virtual</a>
            </div>
        </div>
    </div>
</section><!-- End Clients Section -->
<section class="about d-flex align-items-center justify-content-center" style="padding:2px; background-color: #f6f6f7">
    <div class="container text-center position-relative align-content-center justify-content-center " data-aos="fade-in" data-aos-delay="200">
        <div class="container text-center position-relative" data-aos="fade-in" data-aos-delay="200">
            <div id="carouselExampleIndicators" class="carousel slide carousel-fade" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active text-center">
                        <img class="d-block img-fluid " src="~/Content/assets/img/Banner/promo.jpg" alt="First slide" style="background-attachment: fixed; background-size: cover;">
                    </div>
                    <div class="carousel-item text-center">
                        <img class="d-block img-fluid " src="~/Content/assets/img/Banner/img1.jpg" alt="Second slide">
                    </div>
                    <div class="carousel-item text-center">
                        <img class="d-block img-fluid " src="~/Content/assets/img/Banner/img2.jpg" alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    </div>
</section>
<br />
<div id="main">
    <!-- Page Content -->
    <div class="container">

        <div class="row">
            <div class="col-lg-3 section-bg">
                <h1 class="my-4">Filtros</h1>
                <div class="list-group">
                    @using (Html.BeginForm("Buscar", "Producto", FormMethod.Post))
                    {
                        <div class="input-group">
                            <input type="text" class="form-control list-group-item" name="parameter" id="parameter" placeholder="Buscar producto">
                            <div class="input-group-append">
                                <input class="btn btn-secondary" type="submit" value="Buscar" style="background-color:#009970; border-radius:10px;">
                                <i class="fa fa-search"></i>
                            </div>
                        </div>
                    }
                    @Html.ActionLink("Todos", "Tienda", new { pagina = 1 },
                        new { @class = "btn btn-sm btn-default" })
                    @Html.ActionLink("Sillas", "Buscar", new { parameter = "Silla", pagina = 1 },
                        new { @class = "btn btn-sm btn-default" })
                    @Html.ActionLink("Sillones", "Buscar", new { parameter = "Sillón", pagina = 1  },
                        new { @class = "btn btn-sm btn-default" })
                    @Html.ActionLink("Mesas", "Buscar", new { parameter = "Mesa", pagina = 1  },
                        new { @class = "btn btn-sm btn-default" })
                </div>

            </div>
            <!-- /.col-lg-3 -->

            <div class="col-lg-9">
                <div class="row">

                    @foreach (var item in Model.Resultado)
                    {
                        <div class="col-lg-4 col-md-6 mb-4">
                            <div class="card h-100">
                                <a href="@Url.Action("VistaProducto", "Producto", new { id = item.Id })"><img class="card-img-top" src="~/Content/assets/img/Productos/@item.Imagen" alt=""></a>
                                <hr />
                                <div class="card-body section-title">
                                    <h4 class="card-title">
                                        <a href="@Url.Action("VistaProducto", "Producto", new { id = item.Id })">@item.Nombre</a>
                                    </h4>
                                    <hr />
                                    <h5>$@item.Precio MXN</h5>
                                    <div class="align-content-xl-between align-items-xl-end">
                                        <div class="card-footer">
                                            <small class="card-text text-muted">@item.Descripcion</small>
                                        </div>
                                        <div class="col text-center">
                                            <a href="@Url.Action("VistaProducto", "Producto", new { id = item.Id })" class="btn btn-comprar">Comprar</a>
                                        </div>
                                    </div>


                                </div>

                            </div>
                        </div>
                    }
                </div>
                <!-- /.row -->
                @*Paginador de registros*@
                @if (Model.Resultado.Count() > 0)
                {
                    <span>
                        <strong>@Model.TotalRegistros</strong> registros encontrados
                    </span>
                    <span>&nbsp;|&nbsp;</span>
                    <span>
                        Página <strong>@(Model.PaginaActual)</strong> de
                        <strong>@Model.TotalPaginas</strong>
                    </span>
                    <span>&nbsp;|&nbsp;</span>
                }
                else
                {
                    <span>No hay resultados para esta búsqueda</span>
                    <span>&nbsp;|&nbsp;</span>
                }
                @if (Model.PaginaActual > 1)
                {
                    @Html.ActionLink("<<", "Tienda", new { pagina = 1 },
                        new { @class = "btn btn-sm btn-default"})
                    <span></span>
                    @Html.ActionLink("Anterior", "Tienda", new { pagina = Model.PaginaActual - 1 },
                        new { @class = "btn btn-sm btn-default" });
                }
                else
                {
                    @Html.ActionLink("<<", "Tienda", new { pagina = 1 },
                        new { @class = "btn btn-sm btn-default disabled" })
                    <span></span>
                    @Html.ActionLink("Anterior", "Tienda", new { pagina = 1 },
                        new { @class = "btn btn-sm btn-default disabled" })
                }
                <span></span>
                @if (Model.PaginaActual < Model.TotalPaginas)
                {
                    @Html.ActionLink("Siguiente", "Tienda", new { pagina = Model.PaginaActual + 1 },
                                    new { @class = "btn btn-sm btn-default" })
                    <span></span>
                    @Html.ActionLink(">>", "Tienda", new { pagina = Model.TotalPaginas },
                                    new { @class = "btn btn-sm btn-default" })
                }
                else
                {
                    @Html.ActionLink("Siguiente", "Tienda", new { pagina = Model.TotalPaginas - 1 },
                                    new { @class = "btn btn-sm btn-default disabled" })
                    <span></span>
                    @Html.ActionLink(">>", "Tienda", new { pagina = Model.TotalPaginas },
                                    new { @class = "btn btn-sm btn-default disabled" })
                }
            </div>
            <!-- /.col-lg-9 -->

        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->
</div>
<a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

MerxProject/Views/Producto/ListaProducto.cshtml
@model MerxProject.Models.PaginadorGenerico<MerxProject.Models.Producto>

@{
    ViewBag.Title = "Lista Mueble";

}
<link href="~/Content/assets/css/main.css" rel="stylesheet" />
<h2>Lista de productos</h2>
@if (Session["res"] != null)
{
    string color;
    string mensaje = Session["res"].ToString();
    Session.Remove("res");

    if (Session["tipo"] != null)
    {
        color = "#18ce65";
    }
    else
    {
        color = "#cc0001";
    }
    <div class="panel panel-default" id="current-panel">
        <table class="table table-hover">
            <thead>
                <tr style="background-color:@color">
                    <th>
                        <p style="text-align: center">
                            @mensaje
                        </p>
                    </th>
                    <th>
                        <a href="#current-panel" class="close" data-dismiss="alert" aria-label="close" id="hide">
                            &times;
                        </a>
                    </th>
                </tr>
            </thead>
        </table>
    </div>
    Session.Remove("tipo");

}
@if (ViewBag.error != null)
{
    string error = ViewBag.error;
    ViewBag.error = null;
    <div class="panel panel-default" id="current-panel">
        <table class="table table-hover">
            <thead>
                <tr style="background-color: #cc0001">
                    <th>
                        <p style="text-align: center">
                            @error
                        </p>
                    </th>
                    <th>
                        <a href="#current-panel" class="close" data-dismiss="alert" aria-label="close" id="hide">
                            &times;
                        </a>
                    </th>
                </tr>
            </thead>
        </table>
    </div>
}
<button class="btn btn-success btn-sm pull-right" data-toggle="modal" id="Nuevo">Nuevo</button>
<div class="modal fade" data-keyboard="false" data-backdrop="static" id="idModalRegistrar" tabindex="-1" data-url='@Url.Action("popUpProductos", "Producto", new { applicationUser = "", accion = "1" })'></div>
<br />
@using (Html.BeginForm("BuscarLista", "Producto", FormMethod.Post))
{
    <div class="container">
        <div class="row">
            <div class="col-xs-8">
                <div class="input-group" style="display: inline; vertical-align: top; line-height: 28px;">
                    <select id="orden" name="orden" class="form-control">
                        <option value="">Orden</option>
                        <option value="Asc">Ascendente</option>
                        <option value="Desc">Descendente</option>
                    </select>
                    <select id="categoria" name="categoria" class="form-control">
                        <option value="">Categoria</option>
                        <option value="Nombre">Nombre</option>
                        <option value="Precio">Precio</option>
                        <option value="CatMueble">Categoria Mueble</option>
                        <option value="CatMaterial">Categoría Material</option>
                    </select>
                    <input type="hidden" name="search_param" value="all" id="search_param">
                    <input type="text" class="form-control" name="parameter" placeholder="Search term...">
                    <input type="submit" name="Subir" value="Buscar" class="btn btn-primary" />

                </div>
            </div>
        </div>
    </div>
}


<br />

<table class="table">

    <tr>
        <th>
            Nombre
        </th>
        <th>
            Descripción        
        </th>
        <th>
            Precio
        </th>
        <th>
            Tipo de mueble
        </th>
        <th>
            Tipo de material
        </th>
        <th>
            Imagen
        </th>
    </tr>
    @foreach (var item in Model.Resultado)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Nombre)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Descripcion)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Precio)
    </td>

    <td>
        @Html.DisplayFor(modelItem => item.CategoriaMueble.Nombre)
    </td>

    <td>
        @Html.DisplayFor(modelItem => item.CategoriaMaterial.Nombre)
    </td>
    <td>
        <img src="@Url.Content(item.Imagen)" width="100px" />
    </td>
    <td>
        <button type="submit" class="btn btn-primary btn-sm" data-toggle="modal" id="color_@item.Id" onclick="createModalColor('@Url.Action("popUpProductosColor", "Producto" , new {id=item.Id, accion = "0"})')">Detalle</button>
        <button type="submit" class="btn btn-info btn-sm" data-toggle="modal" id="edit_@item.Id" onclick="createModalEdit('@Url.Action("popUpProductos", "Producto" , new {id=item.Id, accion = "2" })')">Editar Producto</button>
        <button class="btn btn-danger btn-sm" data-toggle="modal" id="delete_@item.Id" data-confirm="¿Estás seguro/a?" onclick="confirmar('@Url.Action("popUpProductos", "Producto" , new {id=item.Id, accion = "3" })')">Eliminar</button>
    </td>
</tr>

    }
</table>
@*Paginador de registros*@
@if (Model.Resultado.Count() > 0)
{
    <span>
        <strong>@Model.TotalRegistros</strong> registros encontrados
    </span>
    <span>&nbsp;|&nbsp;</span>
    <span>
        Página <strong>@(Model.PaginaActual)</strong> de
        <strong>@Model.TotalPaginas</strong>
    </span>
    <span>&nbsp;|&nbsp;</span>
}
else
{
    <span>No hay resultados para esta búsqueda</span>
    <span>&nbsp;|&nbsp;</span>
}
@if (Model.PaginaActual > 1)
{
    @Html.ActionLink("<<", "ListaProducto", new { pagina = 1 },
        new { @class = "btn btn-sm btn-default"})
    <span></span>
    @Html.ActionLink("Anterior", "ListaProducto", new { pagina = Model.PaginaActual - 1 },
        new { @class = "btn btn-sm btn-default" });
}
else
{
    @Html.ActionLink("<<", "ListaProducto", new { pagina = 1 },
        new { @class = "btn btn-sm btn-default disabled" })
    <span></span>
    @Html.ActionLink("Anterior", "ListaProducto", new { pagina = 1 },
        new { @class = "btn btn-sm btn-default disabled" })
}
<span></span>
@if (Model.PaginaActual < Model.TotalPaginas)
{
    @Html.ActionLink("Siguiente", "ListaProducto", new { pagina = Model.PaginaActual + 1 },
                    new { @class = "btn btn-sm btn-default" })
    <span></span>
    @Html.ActionLink(">>", "ListaProducto", new { pagina = Model.TotalPaginas },
                    new { @class = "btn btn-sm btn-default" })
}
else
{
    @Html.ActionLink("Siguiente", "ListaProducto", new { pagina = Model.TotalPaginas - 1 },
                    new { @class = "btn btn-sm btn-default disabled" })
    <span></span>
    @Html.ActionLink(">>", "ListaProducto", new { pagina = Model.TotalPaginas },
                    new { @class = "btn btn-sm btn-default disabled" })
}
<div class="modal fade" data-keyboard="false" data-backdrop="static" id="idModalColor" tabindex="-1"></div>
<div class="modal fade" data-keyboard="false" data-backdrop="static" id="idModalUpdate" tabindex="-1"></div>
<div class="modal fade" data-keyboard="false" data-backdrop="static" id="idModalElminar" tabindex="-1"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript">

    $(document).ready(function () {
        $('#Nuevo').click(function () {
            var url = $('#idModalRegistrar').data('url');
            $.get(url, function (data) {
                $("#idModalRegistrar").html(data);
                $("#idModalRegistrar").modal('show');
            });
        });
    });

    function createModalColor(url) {
        $.get(url, function (data) {
            $("#idModalColor").html(data);
            $("#idModalColor").modal('show');
        });
    }

    function createModalEdit(url) {
        $.get(url, function (data) {
            $("#idModalUpdate").html(data);
            $("#idModalUpdate").modal('show');
        });
    }

    function createModalDelete(url) {
        $.get(url, function (data) {
            $("#idModalElminar").html(data);
            $("#idModalElminar").modal('show');
        });
    }

    function confirmar(url) {
        jQuery(document).ready(function () {
            jQuery('[data-confirm]').click(function (e) {
                if (!confirm(jQuery(this).attr("data-confirm"))) {
                    location.reload(true);
                }
                else {
                    createModalDelete(url);
                }
            })
        })
    }


</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}