MerxProject/Models/Herramienta.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MerxProject.Models
{
    public class Herramienta
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Nombre { get; set; }
        [Required]
        public string Descripcion { get; set; }
        [Required]
        public string Imagen { get; set; }
        [Required]
        public int Cantidad { get; set; }
        [Required]
        public decimal Precio { get; set; }
        public virtual List<DetalleCompra> DetalleCompras { get; set; }
        public int EnUso { get; set; }
        public bool Reportada { get; set; }
        public int idProveedor { get; set; }
    }
}

MerxProject/Controllers/HerramientaController.cs
using MerxProject.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace MerxProject.Controllers
{
    [Authorize(Roles = "Administrador, Empleado")]
    public class HerramientaController : Controller
    {
        private readonly int _RegistrosPorPagina = 10;

        private List<Herramienta> _Herramientas;
        private PaginadorGenerico<Herramienta> _PaginadorHerramientas;

        // GET: Herramienta
        [Authorize (Roles = "Administrador, Empleado")]
        public ActionResult ListaHerramienta(int pagina = 1)
        {
            int _TotalRegistros = 0;

            if (User.IsInRole("Administrador"))
            {
                ViewBag.Admin = true;
            }

            using (ApplicationDbContext DbModel = new ApplicationDbContext())
            {
                _TotalRegistros = DbModel.Herramientas.Count();
                // Obtenemos la 'página de registros' de la tabla Productos
                _Herramientas = DbModel.Herramientas.OrderBy(x => x.Id)
                                                 .Skip((pagina - 1) * _RegistrosPorPagina)
                                                 .Take(_RegistrosPorPagina)
                                                 .ToList();
                // Número total de páginas de la tabla Productos
                var _TotalPaginas = (int)Math.Ceiling((double)_TotalRegistros / _RegistrosPorPagina);
                // Instanciamos la 'Clase de paginación' y asignamos los nuevos valores
                _PaginadorHerramientas = new PaginadorGenerico<Herramienta>()
                {
                    RegistrosPorPagina = _RegistrosPorPagina,
                    TotalRegistros = _TotalRegistros,
                    TotalPaginas = _TotalPaginas,
                    PaginaActual = pagina,
                    Resultado = _Herramientas
                };

                var Reportes = new List<Tuple<int, int>>();
                var ListaReportes = DbModel.HerramientaReportes.ToList();
                
                foreach (var item in _Herramientas)
                {
                    var romper = false;
                    foreach (var rep in ListaReportes)
                    {
                        if (romper) break;
                        if(item.Id == rep.herramienta.Id)
                        {
                            var count = DbModel.HerramientaReportes.Where(x => x.herramienta.Id == rep.herramienta.Id).Count();
                            Reportes.Add(new Tuple<int, int>(item.Id, count));
                            romper = true;
                        }
                        
                    }
                }
                ViewBag.reportes = Reportes;

                return View(_PaginadorHerramientas);
            }
        }

        public ActionResult BuscarHerramienta(string param, int pagina = 1)
        {
            int _TotalRegistros = 0;
            if (!string.IsNullOrWhiteSpace(param))
            {
                using (ApplicationDbContext DbModel = new ApplicationDbContext())
                {
                    _TotalRegistros = DbModel.Herramientas.Where(x => x.Nombre.Contains(param) ||
                                                                    (x.Descripcion.Contains(param)))
                                                                    .OrderBy(x => x.Nombre)
                                                                    .Count();
                    // Obtenemos la 'página de registros' de la tabla Productos
                    _Herramientas = DbModel.Herramientas.Where(x => x.Nombre.Contains(param) ||
                                                                (x.Descripcion.Contains(param)))
                                                                .OrderBy(x => x.Nombre)
                                                                .Skip((pagina - 1) * _RegistrosPorPagina)
                                                                .Take(_RegistrosPorPagina)
                                                                .ToList();
                    // Número total de páginas de la tabla Productos
                    var _TotalPaginas = (int)Math.Ceiling((double)_TotalRegistros / _RegistrosPorPagina);
                    // Instanciamos la 'Clase de paginación' y asignamos los nuevos valores
                    _PaginadorHerramientas = new PaginadorGenerico<Herramienta>()
                    {
                        RegistrosPorPagina = _RegistrosPorPagina,
                        TotalRegistros = _TotalRegistros,
                        TotalPaginas = _TotalPaginas,
                        PaginaActual = pagina,
                        Resultado = _Herramientas
                    };
                    if(_TotalRegistros < 1)
                    {
                        Session["res"] = "No hay resultados";
                        return RedirectToAction("ListaHerramienta");
                    }
                    else
                    {
                        return View("ListaHerramienta", _PaginadorHerramientas);
                    }
                }
            }
            else
            {
                Session["res"] = "No hay resultados";
                return RedirectToAction("ListaHerramienta");
            }
        }

        public ActionResult popUpHerramienta(int? id, string accion)
        {
            string res;

            using (ApplicationDbContext DbModel = new ApplicationDbContext())
            {
                if (accion == "1")
                {
                    ViewBag.Proveedores = DbModel.Proveedores.Include("Persona").ToList();
                    var Herramienta = new Herramienta();
                    ViewBag.Title = "Nuevo";
                    ViewBag.Accion = "1";
                    ViewBag.img = false;
                    return View(Herramienta);
                }
                else if (accion == "2")
                {
                    ViewBag.Proveedores = DbModel.Proveedores.Include("Persona").ToList();
                    var herramienta = DbModel.Herramientas.Find(id);
                    ViewBag.Title = "Editar";
                    ViewBag.Accion = "2";
                    ViewBag.img = true;
                    return View(herramienta);
                }
                else if (accion == "3")
                {
                    var herramienta = DbModel.Herramientas.Find(id);
                    ViewBag.Title = "Eliminar";
                    ViewBag.Accion = "3";
                    ViewBag.img = true;
                    return View(herramienta);
                }
                else if (accion == "4" && id != null)
                {
                    var herramienta = DbModel.Herramientas.Find(id);
                    var usuario = DbModel.Usuarios.Where(x => x.User == User.Identity.Name).FirstOrDefault();
                    var empleado = DbModel.Empleados.Where(x => x.Usuarioss.idUsuario == usuario.idUsuario).FirstOrDefault();
                    var persona = DbModel.Personas.Where(x => x.idPersona == empleado.Personass.idPersona).FirstOrDefault();

                    var Detalle = DbModel.DetalleHerramientas.Where(x => x.Herramienta.Id == herramienta.Id).ToList();

                    res = null;
                    bool Usando = false;

                    foreach (var item in Detalle)
                    {
                        if(item.Empleado == persona.Nombre)
                        {
                            res = "El usuario actual ya tiene en uso esta herramienta";
                            Usando = true;
                            break;
                        }
                    }
                    if (!Usando)
                    {
                        res = ServicioHerramienta(herramienta.Id, "4");
                        Session["tipo"] = "Exito";
                    }
                    
                    
                    Session["res"] = res;
                    
                    return RedirectToAction("ListaHerramienta");
                }
                else if(accion == "5")
                {
                    var herramienta = DbModel.Herramientas.Find(id);

                    var usuario = DbModel.Usuarios.Where(x => x.User == User.Identity.Name).FirstOrDefault();
                    var empleado = DbModel.Empleados.Where(x => x.Usuarioss.idUsuario == usuario.idUsuario).FirstOrDefault();
                    var persona = DbModel.Personas.Where(x => x.idPersona == empleado.Personass.idPersona).FirstOrDefault();

                    var Detalle = DbModel.DetalleHerramientas.Where(x => x.Herramienta.Id == herramienta.Id).ToList();

                    res = null;

                    foreach (var item in Detalle)
                    {
                        if (item.Empleado == persona.Nombre)
                        {
                            res = ServicioHerramienta(herramienta.Id, "5");
                            Session["tipo"] = "Exito";
                            Session["res"] = res;
                            return RedirectToAction("ListaHerramienta");
                        }
                    }
                    Session["res"] = "El usuario actual no tiene esta herramienta en uso";
                    return RedirectToAction("ListaHerramienta");



                }
                return RedirectToAction("ListaHerramienta");
            }
        }

        [HttpPost]
        public async Task<ActionResult> popUpHerramientas(Herramienta herramientas, string accion, HttpPostedFileBase postedFile, int? id)
        {
            string resultado;
            
            using (var DbModel = new ApplicationDbContext())
            {
                if (id != null)
                {
                    if (id != 0)
                    {

MerxProject/Views/Herramienta/ListaHerramienta.cshtml
@model MerxProject.Models.PaginadorGenerico<MerxProject.Models.Herramienta>

@{
    ViewBag.Title = "Lista de herramientas";
    
}
<link href="~/Content/assets/css/main.css" rel="stylesheet" />
<h2>Lista de Herramientas</h2>
@if (Session["res"] != null)
{
    string color;
    string mensaje = Session["res"].ToString();
    Session.Remove("res");

    if (Session["tipo"] != null)
    {
        color = "#18ce65";
    }
    else
    {
        color = "#cc0001";
    }
    <div class="panel panel-default" id="current-panel">
        <table class="table table-hover">
            <thead>
                <tr style="background-color:@color">
                    <th>
                        <p style="text-align: center">
                            @mensaje
                        </p>
                    </th>
                    <th>
                        <a href="#current-panel" class="close" data-dismiss="alert" aria-label="close" id="hide">
                            &times;
                        </a>
                    </th>
                </tr>
            </thead>
        </table>
    </div>
    Session.Remove("tipo");

}
@if (ViewBag.error != null)
{
    string error = ViewBag.error;
    ViewBag.error = null;
    <div class="panel panel-default" id="current-panel">
        <table class="table table-hover">
            <thead>
                <tr style="background-color: #cc0001">
                    <th>
                        <p style="text-align: center">
                            @error
                        </p>
                    </th>
                    <th>
                        <a href="#current-panel" class="close" data-dismiss="alert" aria-label="close" id="hide">
                            &times;
                        </a>
                    </th>
                </tr>
            </thead>
        </table>
    </div>
}
<button class="btn btn-success btn-sm pull-right" data-toggle="modal" id="Nuevo">Nuevo</button>
<div class="modal fade" data-keyboard="false" data-backdrop="static" id="idModalRegistrar" tabindex="-1" data-url='@Url.Action("popUpHerramienta", "Herramienta", new { applicationUser = "", accion = "1" })'></div>
<br />
@using (Html.BeginForm("BuscarHerramienta", "Herramienta", FormMethod.Post))
{
    <div class="container">
        <div class="row">
            <div class="col-xs-8">
                <div class="input-group" style="display: inline; vertical-align: top; line-height: 28px;">
                    <input type="text" class="form-control" name="param" placeholder="Search term...">
                    <input type="submit" name="Subir" value="Buscar" class="btn btn-primary" />

                </div>
            </div>
        </div>
    </div>
}


<br />

<table class="table">

    <tr>
        <th>
            Nombre
        </th>
        <th>
            Descripción
        </th>
        <th>
            Precio
        </th>
        <th>
            Cantidad
        </th>
        <th>
            En uso
        </th>
        <th>
            Imagen
        </th>
        <th>
            Estado
        </th>
    </tr>
    @foreach (var item in Model.Resultado)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Precio)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cantidad)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EnUso)
        </td>
        <td>
            <img src="~/Content/assets/img/Herramienta/@item.Imagen" width="100px" />
        </td>
        <td>
            @if (item.EnUso > 0)
            {
                using (Html.BeginForm("reportarHerramienta", "Herramienta", FormMethod.Get))
                {
                    <input type="hidden" name="Id" value="@item.Id" />
                    <input type="hidden" name="accion" value="6" />
                    <input type="submit" name="name" value="Reportar herramienta" class="btn btn-danger btn-sm" />
                }
            }
            @if (ViewBag.admin != null)
            {
                if (ViewBag.admin && item.Reportada)
                {
                    <button type="submit" class="btn btn-warning btn-sm" data-toggle="modal" id="@item.Id" onclick="createModalReport('@Url.Action("reportarHerramienta", "Herramienta", new { id = item.Id, accion = "7" })')">Ver reportes</button>
                }
            }
            </td>

            <td>
                @if (item.EnUso < item.Cantidad)
                {
                    using (Html.BeginForm("popUpHerramienta", "Herramienta", FormMethod.Get))
                    {
                        <input type="hidden" name="id" value="@item.Id" />
                        <input type="hidden" name="accion" value="4" />
                        <input type="submit" name="name" value="Tomar herramienta" class="btn btn-primary btn-sm" />
                    }
                }
                @using (Html.BeginForm("popUpHerramienta", "Herramienta", FormMethod.Get))
                {
                    <input type="hidden" name="id" value="@item.Id" />
                    <input type="hidden" name="accion" value="5" />
                    <input type="submit" name="name" value="Devolver herramienta" class="btn btn-primary btn-sm" />
                }
            </td>
            <td>
                @if (item.EnUso > 0)
                {
                    if (ViewBag.reportes != null)
                    {
                        var reportes = new List<Tuple<int, int>>();
                        reportes = ViewBag.reportes;
                        if (reportes.Any(x=>x.Item1 == item.Id))
                        {
                            foreach (var rep in reportes)
                            {
                                if (rep.Item1 == item.Id)
                                {
                                    if (rep.Item2 != item.EnUso)
                                    {
                                        <button type="submit" class="btn btn-warning btn-sm" data-toggle="modal" id="@item.Id" onclick="createModalShow('@Url.Action("VerHerramienta", "Herramienta", new { id = item.Id })')">Ver detalle</button>
                                    }
                                }
                            }
                        }
                        else
                        {
                            <button type="submit" class="btn btn-warning btn-sm" data-toggle="modal" id="@item.Id" onclick="createModalShow('@Url.Action("VerHerramienta", "Herramienta", new { id = item.Id })')">Ver detalle</button>
                        }
                    }
                    else
                    {
                        <button type="submit" class="btn btn-warning btn-sm" data-toggle="modal" id="@item.Id" onclick="createModalShow('@Url.Action("VerHerramienta", "Herramienta", new { id = item.Id })')">Ver detalle</button>
                    }

                }
            </td>
            <td>
                <button type="submit" class="btn btn-info btn-sm" data-toggle="modal" id="edit_@item.Id" onclick="createModalEdit('@Url.Action("popUpHerramienta", "Herramienta" , new {id=item.Id, accion = "2" })')">Editar herramienta</button>
                <button class="btn btn-danger btn-sm" data-toggle="modal" id="delete_@item.Id" data-confirm="¿Estás seguro/a?" onclick="confirmar('@Url.Action("popUpHerramienta", "Herramienta" , new {id=item.Id, accion = "3" })')">Eliminar</button>
            </td>
        </tr>

    }
</table>
@*Paginador de registros*@
@if (Model.Resultado.Count() > 0)
{
    <span>
        <strong>@Model.TotalRegistros</strong> registros encontrados
    </span>
    <span>&nbsp;|&nbsp;</span>
    <span>
        Página <strong>@(Model.PaginaActual)</strong> de
        <strong>@Model.TotalPaginas</strong>
    </span>
    <span>&nbsp;|&nbsp;</span>
}
else
{
    <span>No hay resultados para esta búsqueda</span>
    <span>&nbsp;|&nbsp;</span>
}
@if (Model.PaginaActual > 1)
{
    @Html.ActionLink("<<", "ListaProducto", new { pagina = 1 },
        new { @class = "btn btn-sm btn-default"})
    <span></span>
    @Html.ActionLink("Anterior", "ListaProducto", new { pagina = Model.PaginaActual - 1 },
        new { @class = "btn btn-sm btn-default" });
}
else
{
    @Html.ActionLink("<<", "ListaProducto", new { pagina = 1 },
        new { @class = "btn btn-sm btn-default disabled" })
    <span></span>
    @Html.ActionLink("Anterior", "ListaProducto", new { pagina = 1 },
        new { @class = "btn btn-sm btn-default disabled" })
}
<span></span>
@if (Model.PaginaActual < Model.TotalPaginas)
{
    @Html.ActionLink("Siguiente", "ListaProducto", new { pagina = Model.PaginaActual + 1 },
                    new { @class = "btn btn-sm btn-default" })
    <span></span>
    @Html.ActionLink(">>", "ListaProducto", new { pagina = Model.TotalPaginas },
                    new { @class = "btn btn-sm btn-default" })
}
else
{
    @Html.ActionLink("Siguiente", "ListaProducto", new { pagina = Model.TotalPaginas - 1 },
                    new { @class = "btn btn-sm btn-default disabled" })
    <span></span>
    @Html.ActionLink(">>", "ListaProducto", new { pagina = Model.TotalPaginas },
                    new { @class = "btn btn-sm btn-default disabled" })
}
<div class="modal fade" data-keyboard="false" data-backdrop="static" id="idModalReport" tabindex="-1"></div>
<div class="modal fade" data-keyboard="false" data-backdrop="static" id="idModalShow" tabindex="-1"></div>
<div class="modal fade" data-keyboard="false" data-backdrop="static" id="idModalUpdate" tabindex="-1"></div>
<div class="modal fade" data-keyboard="false" data-backdrop="static" id="idModalElminar" tabindex="-1"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
@if (ViewBag.reload != null)
{
    if (ViewBag.reload)
    {
        <script>
            $(document).ready(function () {
                Location.reload(true);
            })
        </script>
    }
}
<script type="text/javascript">


    $(document).ready(function () {
        $('#Nuevo').click(function () {
            var url = $('#idModalRegistrar').data('url');
            $.get(url, function (data) {
                $("#idModalRegistrar").html(data);
                $("#idModalRegistrar").modal('show');
            });
        });
    });

    function createModalReport(url) {
        $.get(url, function (data) {
            $("#idModalReport").html(data);
            $("#idModalReport").modal('show');
        });
    }

    function createModalShow(url) {
        $.get(url, function (data) {
            $("#idModalShow").html(data);
            $("#idModalShow").modal('show');
        });
    }

    function createModalEdit(url) {
        $.get(url, function (data) {
            $("#idModalUpdate").html(data);
            $("#idModalUpdate").modal('show');
        });
    }

    function createModalDelete(url) {
        $.get(url, function (data) {
            $("#idModalElminar").html(data);
            $("#idModalElminar").modal('show');
        });
    }

    function confirmar(url) {
        jQuery(document).ready(function () {
            jQuery('[data-confirm]').click(function (e) {
                if (!confirm(jQuery(this).attr("data-confirm"))) {
                    location.reload(true);
                }
                else {
                    createModalDelete(url);
                }
            })
        })
    }


</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MerxProject/Views/Herramienta/popUpHerramienta.cshtml
@model MerxProject.Models.Herramienta

@{
    Layout = null;
}

<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <button class="close" data-dismiss="modal" onclick="location.reload(true)">&times;</button>
                        <h4 class="modal-title">@ViewBag.title</h4>
                    </div>
                    <div class="modal-body">
                        @using (Html.BeginForm("popUpHerramientas", "Herramienta", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">
                                @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                                    @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    <div class="checkbox">
                                        @Html.EditorFor(model => model.Nombre)
                                        @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Precio, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Precio, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Cantidad, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Cantidad, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Cantidad, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.EnUso, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @if (ViewBag.img)
                                    {
                                        @Html.EditorFor(model => model.EnUso, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.EnUso, "", new { @class = "text-danger" })

                                    }
                                    else
                                    {
                                        @Html.EditorFor(model => model.EnUso, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                                        @Html.ValidationMessageFor(model => model.EnUso, "", new { @class = "text-danger" })
                                    }
                                </div>
                            </div>

                            @if (ViewBag.Proveedores != null)
                            {
                                <div class="form-group">
                                    @Html.Label("Proveedor", htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.DropDownListFor(model => model.idProveedor, new SelectList(ViewBag.Proveedores, "Id", "Persona.Nombre"), "Seleccione", new { @class = "form-control" })
                                        @if (ViewBag.Proveedor != null)
                                        {
                                            <input type="hidden" name="idProveedor" value="@ViewBag.Proveedor.Id" />
                                        }
                                    </div>
                                </div>
                            }
                            <div class="form-group">
                                <label class="control-label col-md-2">Imagen</label>
                                <div class="col-md-10">
                                    @if (ViewBag.img)
                                    {
                                        <img class="card-img-top" src="~/Content/assets/img/Herramientas/@Url.Content(Model.Imagen)" width="100px" alt="">
                                    }
                                    <br />
                                    <span>Seleccionar archivo:</span>
                                    <input type="file" name="postedFile" required />
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="hidden" name="accion" value="@ViewBag.Accion" />
                                    <input type="hidden" name="id" value="@Model.Id" />
                                    <input type="submit" value="@ViewBag.title" class="btn btn-default" />
                                </div>
                            </div>
                        </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}