MerxProject/Models/Empleado.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MerxProject.Models
{
    public class Empleado
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public DateTime FechaIngreso { get; set; }

        public virtual List<Compra> Compras { get; set; }
        public virtual Persona Personass { get; set; }
        public virtual Usuario Usuarioss { get; set; }
    }
}

MerxProject/Controllers/EmpleadoController.cs
using MerxProject.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace MerxProject.Controllers
{
    public class EmpleadoController : Controller
    {
        private ApplicationUserManager _userManager;

        private readonly int _RegistrosPorPagina = 10;

        private List<Empleado> _Empleados;
        private PaginadorGenerico<Empleado> _PaginadorEmpleado;
        

        [HttpGet]
        public ActionResult PopUpEmpleados(int? Id, string accion)
        {
            using (ApplicationDbContext DbModel = new ApplicationDbContext())
            {
                if (accion == "1")
                {
                    ViewBag.title = "Nuevo";
                    ViewBag.Accion = "1";
                    return View();
                }
                else if (accion == "2")
                {
                    var empleado = DbModel.Empleados.Find(Id);
                    empleado.Usuarioss = (Usuario)empleado.Usuarioss;
                    empleado.Personass = (Persona)empleado.Personass;
                    ViewBag.pass = empleado.Usuarioss.Password;
                    ViewBag.puesto = empleado.Usuarioss.Rol;
                    ViewBag.title = "Editar";
                    ViewBag.Accion = "2";
                    return View(empleado);
                }
                else if (accion == "3")
                {
                    var empleado = DbModel.Empleados.Find(Id);
                    empleado.Usuarioss = (Usuario)empleado.Usuarioss;
                    empleado.Personass = (Persona)empleado.Personass;
                    ViewBag.pass = empleado.Usuarioss.Password;
                    ViewBag.puesto = empleado.Usuarioss.Rol;
                    ViewBag.title = "Eliminar";
                    ViewBag.Accion = "3";
                    return View(empleado);
                }
            }
            return RedirectToAction("ListaEmpleado");
        }

        [HttpPost]
        public async Task<ActionResult> PopUpEmpleados(Empleado empleados, string accion, string rol, string password)
        {
            string res;
            using (ApplicationDbContext DbModel = new ApplicationDbContext())
            {
                // Si el applicationUser viene diferente de null, significa que el usuario quiere Editar
                if (empleados.Id > 0 && accion == "2")
                {
                    // Edición
                    var empleado = DbModel.Empleados.Find(empleados.Id);
                    empleados.Personass.Correo = empleado.Personass.Correo;

                    if (empleado != null)
                    {
                        try
                        {
                            empleados.FechaIngreso = DateTime.Now;
                            empleados.Usuarioss.Rol = rol;
                            empleados.Usuarioss.Password = password;


                            if (empleados.Personass.Correo != empleado.Personass.Correo && empleados.Usuarioss.Rol == rol)
                            {
                                var userDel = DbModel.Users.Where(x => x.UserName == empleado.Usuarioss.User).FirstOrDefault();
                                var userName = userDel.Id;
                                var RoleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(DbModel));
                                var rolDel = RoleManager.FindByName(empleados.Usuarioss.Rol).Name;

                                UserManager.RemoveFromRole(userName, rolDel);
                                DbModel.Users.Remove(userDel);

                                var user = new ApplicationUser { UserName = empleados.Usuarioss.User, Email = empleados.Personass.Correo, idPersona = empleados.Personass.idPersona, IdUsuario = empleados.Usuarioss.idUsuario };
                                var result = await UserManager.CreateAsync(user, empleados.Usuarioss.Password);
                                if (result.Succeeded)
                                {
                                    string code = await UserManager.GenerateEmailConfirmationTokenAsync(user.Id);
                                    var callbackUrl = Url.Action("ConfirmEmail", "Account", new { userId = user.Id, code = code }, protocol: Request.Url.Scheme);
                                    await UserManager.SendEmailAsync(user.Id, "Confirmar cuenta", callbackUrl);

                                    DbModel.Empleados.AddOrUpdate(empleados);
                                    DbModel.Usuarios.AddOrUpdate(empleados.Usuarioss);
                                    DbModel.Personas.AddOrUpdate(empleados.Personass);
                                    DbModel.SaveChanges();

                                    var UsuarioNuevo = UserManager.FindByEmail(empleados.Personass.Correo).Id;
                                    UserManager.AddToRole(UsuarioNuevo, rolDel);

                                    res = "Actualización realizada";
                                    Session["res"] = res;
                                    Session["tipo"] = "Exito";
                                    return RedirectToAction("ListaEmpleado");
                                }
                                else
                                {
                                    Session["res"] = result.Errors.ToList();
                                    return RedirectToAction("ListaEmpleado");
                                }
                            }
                            else if (empleados.Personass.Correo == empleado.Personass.Correo && empleados.Usuarioss.Rol != empleado.Usuarioss.Rol)
                            {
                                var userDel = DbModel.Users.Where(x => x.Email == empleado.Personass.Correo).FirstOrDefault();
                                var userName = userDel.Id;
                                var RoleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(DbModel));
                                var rolAnterior = RoleManager.FindByName(empleado.Usuarioss.Rol).Id;

                                if (!RoleManager.RoleExists(empleados.Usuarioss.Rol))
                                {
                                    var role = new IdentityRole();
                                    role.Name = rol;
                                    RoleManager.Create(role);
                                }

                                var rolNuevo = RoleManager.FindByName(rol);

                                UserManager.RemoveFromRole(userName, rolAnterior);
                                UserManager.AddToRole(userDel.Id,rolNuevo.Name);

                                DbModel.Empleados.AddOrUpdate(empleados);
                                DbModel.Usuarios.AddOrUpdate(empleados.Usuarioss);
                                DbModel.Personas.AddOrUpdate(empleados.Personass);
                                DbModel.SaveChanges();

                                res = "Actualización realizada";
                                Session["res"] = res;
                                Session["tipo"] = "Exito";
                                return RedirectToAction("ListaEmpleado");
                            }
                            else
                            {
                                DbModel.Empleados.AddOrUpdate(empleados);
                                DbModel.Usuarios.AddOrUpdate(empleados.Usuarioss);
                                DbModel.Personas.AddOrUpdate(empleados.Personass);
                                DbModel.SaveChanges();

                                res = "Actualización realizada";
                                Session["res"] = res;
                                Session["tipo"] = "Exito";
                                return RedirectToAction("ListaEmpleado");
                            }
                        }
                        catch (Exception ex)
                        {
                            res = ex.Message;
                            ViewBag.res = res;
                            return RedirectToAction("ListaEmpleado");
                        }
                    }

                }
                else if (empleados.Id > 0 && accion == "3")
                {
                    // Eliminación
                    var usuario = DbModel.Usuarios.ToList();
                    var persona = DbModel.Personas.ToList();
                    var empleado = DbModel.Empleados.Find(empleados.Id);

                    if (empleado != null)
                    {

                        try
                        {
                            var user = DbModel.Users.Where(x => x.Email == empleado.Personass.Correo).FirstOrDefault().Id;
                            var userDel = DbModel.Users.Where(x => x.Email == empleado.Personass.Correo).FirstOrDefault();
                            var RoleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(DbModel));
                            var rolDel = RoleManager.FindByName(empleado.Usuarioss.Rol).Id;
                            UserManager.RemoveFromRole(user, rolDel);

                            DbModel.Users.Remove(userDel);
                            DbModel.Usuarios.Remove(empleado.Usuarioss);
                            DbModel.Personas.Remove(empleado.Personass);
                            DbModel.Empleados.Remove(empleado);
                            DbModel.SaveChanges();

                            res = "Eliminación finalizada";
                            Session["res"] = res;
                            Session["tipo"] = "Exito";
                            return RedirectToAction("ListaEmpleado");
                        }

MerxProject/Views/Empleado/ListaEmpleado.cshtml
@model MerxProject.Models.PaginadorGenerico<MerxProject.Models.Empleado>

@{
    ViewBag.Title = "ListaEmpleado";
}

<h2>Lista de Empleados</h2>

@if (Session["res"] != null)
{
    string color;
    string mensaje = Session["res"].ToString();
    Session.Remove("res");

    if (Session["tipo"] != null)
    {
        color = "#18ce65";
    }
    else
    {
        color = "#cc0001";
    }
    <div class="panel panel-default" id="current-panel">
        <table class="table table-hover">
            <thead>
                <tr style="background-color:@color">
                    <th>
                        <p style="text-align: center">
                            @mensaje
                        </p>
                    </th>
                    <th>
                        <a href="#current-panel" class="close" data-dismiss="alert" aria-label="close" id="hide">
                            &times;
                        </a>
                    </th>
                </tr>
            </thead>
        </table>
    </div>
    Session.Remove("tipo");

}
@if (ViewBag.error != null)
{
    string error = ViewBag.error;
    ViewBag.error = null;
    <div class="panel panel-default" id="current-panel">
        <table class="table table-hover">
            <thead>
                <tr style="background-color: #cc0001">
                    <th>
                        <p style="text-align: center">
                            @error
                        </p>
                    </th>
                    <th>
                        <a href="#current-panel" class="close" data-dismiss="alert" aria-label="close" id="hide">
                            &times;
                        </a>
                    </th>
                </tr>
            </thead>
        </table>
    </div>
}
<button class="btn btn-success btn-sm pull-right" data-toggle="modal" id="Nuevo">Nuevo</button>
<div class="modal fade" data-keyboard="false" data-backdrop="static" id="idModalRegistrar" tabindex="-1"
     data-url='@Url.Action("PopUpEmpleados", "Empleado", new { applicationUser = "", accion = "1" })'></div>

<br />

@using (Html.BeginForm("BuscarEmpleado", "Empleado", FormMethod.Post))
{
    <div class="container">
        <div class="row">
            <div class="col-xs-8">
                <div class="input-group" style="display: inline; vertical-align: top; line-height: 28px;">
                    <input type="text" class="form-control" name="param" placeholder="Search term...">
                    <input type="submit" name="Subir" value="Buscar" class="btn btn-primary" />

                </div>
            </div>
        </div>
    </div>
}

<br />

<table class="table">
    <tr>
        <th>
            Nombre
        </th>
        <th>
            Telefono
        </th>
        <th>
            Correo
        </th>
        <th>
            Nombre de usuario
        </th>
        <th>
            Contraseña
        </th>
        <th>
            Rol
        </th>
        <th>
            Fecha de ingreso
        </th>
    </tr>

    @foreach (var item in Model.Resultado)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Personass.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Personass.Telefono)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Personass.Correo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Usuarioss.User)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Usuarioss.Password)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Usuarioss.Rol)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaIngreso)
            </td>
            <td>
                @if (ViewBag.user != item.Usuarioss.User)
                {
                    <button type="submit" class="btn btn-info btn-sm" data-toggle="modal" id="edit_@item.Id"
                            onclick="createModal('@Url.Action("PopUpEmpleados", "Empleado" , new {id=item.Id, accion = "2" })')">
                        Editar
                    </button>

                    <button type="submit" class="btn btn-danger btn-sm" data-toggle="modal" id="delete_@item.Id"
                            onclick="createModal('@Url.Action("PopUpEmpleados", "Empleado", new { id = item.Id, accion = "3" })')">
                        Eliminar
                    </button>
                }
            </td>
        </tr>
    }
</table>

@*Paginador de registros*@
@if (Model.Resultado.Count() > 0)
{
    <span>
        <strong>@Model.TotalRegistros</strong> registros encontrados
    </span>
    <span>&nbsp;|&nbsp;</span>
    <span>
        Página <strong>@(Model.PaginaActual)</strong> de
        <strong>@Model.TotalPaginas</strong>
    </span>
    <span>&nbsp;|&nbsp;</span>
}
else
{
    <span>No hay resultados para esta búsqueda</span>
    <span>&nbsp;|&nbsp;</span>
}
@if (Model.PaginaActual > 1)
{
    @Html.ActionLink("<<", "ListaEmpleado", new { pagina = 1 },
        new { @class = "btn btn-sm btn-default"})
    <span></span>
    @Html.ActionLink("Anterior", "ListaEmpleado", new { pagina = Model.PaginaActual - 1 },
        new { @class = "btn btn-sm btn-default" });
}
else
{
    @Html.ActionLink("<<", "ListaEmpleado", new { pagina = 1 },
        new { @class = "btn btn-sm btn-default disabled" })
    <span></span>
    @Html.ActionLink("Anterior", "ListaEmpleado", new { pagina = 1 },
        new { @class = "btn btn-sm btn-default disabled" })
}
<span></span>
@if (Model.PaginaActual < Model.TotalPaginas)
{
    @Html.ActionLink("Siguiente", "ListaEmpleado", new { pagina = Model.PaginaActual + 1 },
                    new { @class = "btn btn-sm btn-default" })
    <span></span>
    @Html.ActionLink(">>", "ListaEmpleado", new { pagina = Model.TotalPaginas },
                    new { @class = "btn btn-sm btn-default" })
}
else
{
    @Html.ActionLink("Siguiente", "ListaEmpleado", new { pagina = Model.TotalPaginas - 1 },
                    new { @class = "btn btn-sm btn-default disabled" })
    <span></span>
    @Html.ActionLink(">>", "ListaEmpleado", new { pagina = Model.TotalPaginas },
                    new { @class = "btn btn-sm btn-default disabled" })
}

<div class="modal fade" data-keyboard="false" data-backdrop="static" id="idModalUpdate" tabindex="-1"></div>
<div class="modal fade" data-keyboard="false" data-backdrop="static" id="idModalElminar" tabindex="-1"></div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript">

    $(document).ready(function () {
        $('#Nuevo').click(function () {
            var url = $('#idModalRegistrar').data('url');
            $.get(url, function (data) {
                $("#idModalRegistrar").html(data);
                $("#idModalRegistrar").modal('show');
            });
        });
    });


    function createModal(url) {
        $.get(url, function (data) {
            $("#idModalUpdate").html(data);
            $("#idModalUpdate").modal('show');
        });

    }

    function createModal(url) {
        $.get(url, function (data) {
            $("#idModalElminar").html(data);
            $("#idModalElminar").modal('show');
        });

    }
    


</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MerxProject/Views/Empleado/PopUpEmpleados.cshtml
@model MerxProject.Models.Empleado

<h2>PopUpEmpleados</h2>

<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <div class="modal-dialog modal-lg" style="">
                <div class="modal-content">
                    <div class="modal-header">
                        <button class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">@ViewBag.title</h4>
                    </div>
                    <div class="modal-body">
                        @using (Html.BeginForm("PopUpEmpleados", "Empleado", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            @Html.AntiForgeryToken()
                            //Informacion de persona
                        <section id="sectionEmp" style="" >
                            <div class="form-horizontal">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                                        @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Personass.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Personass.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Personass.Nombre, "", new { @class = "text-danger" })
                                    </div>
                                </div>


                                @Html.HiddenFor(model => model.Personass.idPersona, new { htmlAttributes = new { @class = "form-control",
                                    @disabled = "disabled" }})
                                @Html.HiddenFor(model => model.Usuarioss.idUsuario, new { htmlAttributes = new { @class = "form-control",
                                    @disabled = "disabled" }})


                                <div class="form-group">
                                    @Html.LabelFor(model => model.Personass.Correo, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Personass.Correo, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Personass.Correo, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Personass.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Personass.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Personass.Direccion, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Personass.CodigoPostal, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Personass.CodigoPostal, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Personass.CodigoPostal, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Personass.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Personass.Estado, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Personass.Estado, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Personass.Ciudad, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Personass.Ciudad, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Personass.Ciudad, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Personass.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Personass.Telefono, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Personass.Telefono, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                        </section>
                        <aside id="asideEmp">
                            <div class="form-horizontal">

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Usuarioss.Rol, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        <select name="rol" id="rol" class="form-control" required>
                                            @if (ViewBag.puesto != null && ViewBag.puesto == "Administrador")
                                            {
                                                <option value="Administrador" selected>Administrador</option>
                                                <option value="Empleado">Empleado</option>
                                            }
                                            else
                                            {
                                                <option value ="Administrador"> Administrador </option>
                                                <option value ="Empleado" selected> Empleado </option>
                                            }
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-10">
                                        <label class="control-label">La contraseña debe tener mínimo 14 caracteres y un signo especial</label>
                                    </div>
                                </div>
                                <div class="form-group" id="password">
                                    @Html.LabelFor(model => model.Usuarioss.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @if (ViewBag.pass != null)
                                        {
                                            <input type="password" name="password" id="pass" class="form-control" required value="@ViewBag.pass"/>
                                        }
                                        else
                                        {
                                            <input type="password" name="password" id="pass" class="form-control" required />
                                        }
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Usuarioss.User, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Usuarioss.User, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Usuarioss.User, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="hidden" name="accion" value="@ViewBag.Accion" />
                                        <input type="submit" value="@ViewBag.title" class="btn btn-default" />
                                    </div>
                                </div>
                            </div>
                        </aside>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}