MerxProject/Models/Compra.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MerxProject.Models
{
    public class Compra
    {
        [Key]
        public int Id { get; set; }
        [MaxLength(20)]
        public string Folio { get; set; }
        public decimal MontoTotal { get; set; }
        [Required]
        public DateTime FechaRegistro { get; set; }
        [Required]
        public int Estatus { get; set; }

        public string DS_Estatus { get; set; }

        // Llaves foráneas
        //public int? IdProveedor { get; set; }
        //public int? IdEmpleado { get; set; }

        // Relaciones con otras tablas
        //public virtual List<DetalleCompra> DetalleCompra { get; set; }
        public Proveedor Proveedor { get; set; }
        public Empleado Empleado { get; set; }
    }

    public enum EstatusC
    {
        Vacía = 0,
        Pendiente = 1,
        Confirmada = 2,
        Entregada = 3,
        Cancelada = 4,
        Incompleta = 5
    }
}

MerxProject/Controllers/ComprasController.cs
using MerxProject.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace MerxProject.Controllers
{
    public class ComprasController : Controller
    {
        private readonly int _RegistrosPorPagina = 10;

        private List<Compra> _Compras;
        private List<DetalleCompra> _DetalleCompras;
        private PaginadorGenerico<Compra> _PaginadorCompras;
        private PaginadorGenerico<DetalleCompra> _PaginadorDetalleCompra;

        [AllowAnonymous]
        [HttpGet]
        public ActionResult popUpCompras(int? Id, string accion)
        {
            using (ApplicationDbContext DbModel = new ApplicationDbContext())
            {
                ViewBag.Proveedores = DbModel.Proveedores.Include("Persona").ToList();
                ViewBag.Empleados = DbModel.Empleados.Include("Personass").Include("Usuarioss").ToList();
                if (accion == "1")
                {
                    var correo = User.Identity.Name;
                    var compra = new Compra();
                    compra.FechaRegistro = DateTime.Now;
                    compra.Estatus = 0;
                    compra.DS_Estatus = ((EstatusC[])(Enum.GetValues(typeof(EstatusC))))[Convert.ToInt32(compra.Estatus)].ToString();
                    if (correo != "")
                    {
                        var usuario = DbModel.Usuarios.Where(x => x.User == User.Identity.Name).FirstOrDefault();
                        var empleado = DbModel.Empleados.Where(x => x.Usuarioss.idUsuario == usuario.idUsuario).FirstOrDefault();
                        var Persona = DbModel.Personas.Where(x => x.idPersona == empleado.Personass.idPersona).FirstOrDefault();
                        // var Persona = DbModel.Personas.FirstOrDefault(x => x.Correo == correo);
                        empleado.Personass = Persona;
                        compra.Empleado = DbModel.Empleados.
                            Include("Personass").
                            FirstOrDefault(x => x.Personass.idPersona == Persona.idPersona);
                    }
                    ViewBag.title = "Nuevo";
                    ViewBag.Accion = "1";
                    return View("popUpCompras", compra);
                }
                else if (accion == "2")
                {
                    var compra = DbModel.Compras.Find(Id);
                    compra.DS_Estatus = ((EstatusC[])(Enum.GetValues(typeof(EstatusC))))[Convert.ToInt32(compra.Estatus)].ToString();
                    ViewBag.title = "Editar";
                    ViewBag.Accion = "2";
                    return View("popUpCompras", compra);
                }
                else if (accion == "3")
                {
                    var compra = DbModel.Compras.Find(Id);
                    ViewBag.title = "Cancelar";
                    ViewBag.Accion = "3";
                    return View("popUpCompras", compra);
                }
                else if (accion == "5")
                {
                    var compra = DbModel.Compras.Find(Id);
                    ViewBag.title = "Marcar como Entregada";
                    ViewBag.Accion = "5";
                    return View("popUpCompras", compra);
                }

            }
            return RedirectToAction("popUpCompras");
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<ActionResult> popUpCompras(Compra compras, string accion, HttpPostedFileBase postedFile)
        {
            string resultado;
            using (ApplicationDbContext DbModel = new ApplicationDbContext())
            {
                // Si el applicationUser viene diferente de null, significa que el usaurio quiere Editar
                if (compras.Id > 0 && accion == "2")
                {
                    // Edición
                    var compra = DbModel.Compras.Include("Proveedor").Include("Empleado").Where(e => e.Id == compras.Id).FirstOrDefault();

                    if (compra != null)
                    {
                        var proveedor = DbModel.Proveedores.Find(compras.Proveedor.Id);
                        var empleado = DbModel.Empleados.Find(compras.Empleado.Id);

                        if (proveedor != null && empleado != null)
                        {

                            compra.Proveedor = proveedor;
                            compra.Empleado = empleado;
                            compra.Folio = compra.Proveedor.RFC.Substring(0, 4).ToUpper() +
                                                compras.FechaRegistro.Year + compras.FechaRegistro.Month +
                                                compras.FechaRegistro.Day + compras.FechaRegistro.Hour +
                                                compras.FechaRegistro.Minute + compras.FechaRegistro.Second;
                            try
                            {
                                DbModel.Compras.AddOrUpdate(compra);
                                DbModel.SaveChanges();
                                resultado = "Actualización realizada";
                                ViewBag.res = resultado;
                                Session["res"] = resultado;
                                Session["tipo"] = "Exito";
                                return RedirectToAction("ListaCompras");

                            }
                            catch (Exception ex)
                            {
                                resultado = ex.Message;
                                ViewBag.res = resultado;
                                Session["res"] = resultado;
                                return RedirectToAction("ListaCompras");
                            }
                        }
                    }

                }
                else if (compras.Id > 0 && accion == "3")
                {
                    // Eliminación
                    var compra = DbModel.Compras.Find(compras.Id);

                    if (compra != null)
                    {

                        try
                        {
                            compra.Estatus = 4;
                            DbModel.Compras.AddOrUpdate(compra);
                            DbModel.SaveChanges();
                            resultado = "Cancelación finalizada";
                            ViewBag.res = resultado;

                            Session["res"] = resultado;
                            Session["tipo"] = "Exito";
                            return RedirectToAction("ListaCompras");
                        }
                        catch (Exception ex)
                        {
                            resultado = ex.Message;
                            ViewBag.res = resultado;

                            Session["res"] = resultado;
                            return RedirectToAction("ListaCompras");
                        }
                    }
                }
                else if (compras.Id > 0 && accion == "5")
                {
                    // Entrega
                    //var compra = DbModel.Compras.Find(compras.Id);
                    var compra = DbModel.Compras.Include("Empleado.Personass").Include("Proveedor.Persona").Where(e => e.Id == compras.Id).FirstOrDefault();

                    if (compra != null)
                    {
                        var proveedor = DbModel.Proveedores.Find(compra.Proveedor.Id);
                        var empleado = DbModel.Empleados.Find(compra.Empleado.Id);

                        if (proveedor != null && empleado != null)
                        {

                            compras.Proveedor = proveedor;
                            compras.Empleado = empleado;
                            try
                            {
                                compra.Estatus = 3;
                                DbModel.Compras.AddOrUpdate(compra);

                                var detalles = DbModel.DetalleCompra.Include("MateriaPrima").Include("Herramienta").Where(e => e.Compra.Id == compra.Id).ToList();
                                if (detalles.Count() > 0)
                                {
                                    foreach (DetalleCompra det in detalles)
                                    {
                                        if (det.Herramienta != null)
                                        {
                                            var herramienta = DbModel.Herramientas.Where(e => e.Id == det.Herramienta.Id).FirstOrDefault();
                                            herramienta.Cantidad += Convert.ToInt32(Math.Floor(det.Cantidad));
                                            DbModel.Herramientas.AddOrUpdate(herramienta);
                                        }
                                        else if (det.MateriaPrima != null)
                                        {
                                            var materiaPrima = DbModel.Materiales.Where(e => e.Id == det.MateriaPrima.Id).FirstOrDefault();
                                            materiaPrima.Cantidad += Convert.ToInt32(Math.Floor(det.Cantidad));
                                            DbModel.Materiales.AddOrUpdate(materiaPrima);
                                        }
                                    }
                                }
                                DbModel.SaveChanges();
                                resultado = "Entrega finalizada";
                                ViewBag.res = resultado;

                                Session["res"] = resultado;
                                Session["tipo"] = "Exito";
                                return RedirectToAction("ListaCompras");
                            }

                            catch (Exception ex)
                            {
                                resultado = ex.Message;

MerxProject/Views/Compras/ListaCompras.cshtml
@model MerxProject.Models.PaginadorGenerico<MerxProject.Models.Compra>

@{
    ViewBag.Title = "ListaCompras";
}
<h2>Compras</h2>

@if (Session["res"] != null)
{
    string color;
    string mensaje = Session["res"].ToString();
    Session.Remove("res");


    if (Session["tipo"] != null)
    {
        color = "#18ce65";
    }
    else
    {
        color = "#cc0001";
    }
    <div class="panel panel-default" id="current-panel">
        <table class="table table-hover">
            <thead>
                <tr style="background-color:@color">
                    <th>
                        <p style="text-align: center">
                            @mensaje
                        </p>
                    </th>
                    <th>
                        <a href="#current-panel" class="close" data-dismiss="alert" aria-label="close" id="hide">
                            &times;
                        </a>
                    </th>
                </tr>
            </thead>
        </table>
    </div>
    Session.Remove("tipo");
}
@if (ViewBag.error != null)
{
    string error = ViewBag.error;
    ViewBag.error = null;
    <div class="panel panel-default" id="current-panel">
        <table class="table table-hover">
            <thead>
                <tr style="background-color: #cc0001">
                    <th>
                        <p style="text-align: center">
                            @error
                        </p>
                    </th>
                    <th>
                        <a href="#current-panel" class="close" data-dismiss="alert" aria-label="close" id="hide">
                            &times;
                        </a>
                    </th>
                </tr>
            </thead>
        </table>
    </div>
}

@using (Html.BeginForm("BuscarLista", "Compras", FormMethod.Post))
{
    <div class="container">
        <div class="row">
            <div class="col-xs-8">
                <div class="input-group" style="display: inline; vertical-align: top; line-height: 28px;">
                    <input type="text" class="form-control" name="parameter" placeholder="Buscar...">
                    <input type="submit" name="Subir" value="Buscar" class="btn btn-primary" />
                </div>
            </div>
        </div>
    </div>
}
<br />
<button class="btn btn-success btn-sm pull-right" data-toggle="modal" id="Nuevo" onclick="createModal('@Url.Action("popUpCompras", "Compras", new { applicationUser = "", accion = "1" })')">Nuevo</button>


<br />
<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Folio")
        </th>
        <th>
            @Html.DisplayName("Proveedor")
        </th>
        <th>
            @Html.DisplayName("Empleado")
        </th>
        <th>
            @Html.DisplayName("Monto Total")
        </th>
        <th>
            @Html.DisplayName("Fecha de Registro")
        </th>
        <th>
            @Html.DisplayName("Estatus")
        </th>
    </tr>

    @foreach (var item in Model.Resultado)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Folio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Proveedor.Persona.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Empleado.Personass.Nombre)
            </td>
            <td>
                $
                @Html.DisplayFor(modelItem => item.MontoTotal)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaRegistro)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DS_Estatus)
            </td>
            <td>
                @Html.ActionLink("Detalles", "ListaDetalleCompra", new { idCompra = item.Id, accion = "4" },
                    new { @class = "btn btn-sm btn-warning" })
                @if (item.Estatus < 2)
                {
                    if (item.Estatus == 0)
                    {
                        <button type="submit" class="btn btn-info btn-sm" data-toggle="modal" id="edit_@item.Id"
                                onclick="createModal('@Url.Action("popUpCompras", "Compras", new { id = item.Id, accion = "2" })')">
                            Editar
                        </button>
                    }
                    if (item.Estatus > 0)
                    {
                        <button type="submit" class="btn btn-info btn-sm" data-toggle="modal" id="edit_@item.Id"
                                disabled>
                            Editar
                        </button>
                    }
                    <button class="btn btn-danger btn-sm" data-toggle="modal" id="Elimninar" id="delete_@item.Id"
                            onclick="createModal('@Url.Action("popUpCompras", "Compras", new { id = item.Id, accion = "3" })')">
                        Cancelar
                    </button>
                    if (item.Estatus > 0)
                    {
                        <button type="submit" class="btn btn-dark btn-sm" data-toggle="modal" id="ent_@item.Id"
                                onclick="createModal('@Url.Action("popUpCompras", "Compras", new { id = item.Id, accion = "5" })')">
                            Marcar como Entregada
                        </button>
                    }
                    if (item.Estatus == 0)
                    {
                        <button type="submit" class="btn btn-dark btn-sm" data-toggle="modal" id="ent_@item.Id"
                                disabled>
                            Marcar como Entregada
                        </button>
                    }
                }
                @if (item.Estatus >= 2)
                {
                    <button type="submit" class="btn btn-info btn-sm" data-toggle="modal" id="edit_@item.Id"
                            disabled>
                        Editar
                    </button>
                    <button class="btn btn-danger btn-sm" data-toggle="modal" id="Elimninar" id="delete_@item.Id"
                            disabled>
                        Cancelar
                    </button>
                    <button type="submit" class="btn btn-dark btn-sm" data-toggle="modal" id="ent_@item.Id"
                            disabled>
                        Marcar como Entregada
                    </button>
                }
            </td>
        </tr>

    }
</table>



@*Paginador de registros*@
@if (Model.Resultado.Count() > 0)
{
    <span>
        <strong>@Model.TotalRegistros</strong> registros encontrados
    </span>
    <span>&nbsp;|&nbsp;</span>
    <span>
        Página <strong>@(Model.PaginaActual)</strong> de
        <strong>@Model.TotalPaginas</strong>
    </span>
    <span>&nbsp;|&nbsp;</span>
}
else
{
    <span>No hay resultados para esta búsqueda</span>
    <span>&nbsp;|&nbsp;</span>
}
@if (Model.PaginaActual > 1)
{
    @Html.ActionLink("<<", "ListaCompras", new { pagina = 1 },
        new { @class = "btn btn-sm btn-default"})
    <span></span>
    @Html.ActionLink("Anterior", "ListaCompras", new { pagina = Model.PaginaActual - 1 },
        new { @class = "btn btn-sm btn-default" });
}
else
{
    @Html.ActionLink("<<", "ListaCompras", new { pagina = 1 },
        new { @class = "btn btn-sm btn-default disabled" })
    <span></span>
    @Html.ActionLink("Anterior", "ListaCompras", new { pagina = 1 },
        new { @class = "btn btn-sm btn-default disabled" })
}
<span></span>
@if (Model.PaginaActual < Model.TotalPaginas)
{
    @Html.ActionLink("Siguiente", "ListaCompras", new { pagina = Model.PaginaActual + 1 },
                    new { @class = "btn btn-sm btn-default" })
    <span></span>
    @Html.ActionLink(">>", "ListaCompras", new { pagina = Model.TotalPaginas },
                    new { @class = "btn btn-sm btn-default" })
}
else
{
    @Html.ActionLink("Siguiente", "ListaCompras", new { pagina = Model.TotalPaginas - 1 },
                    new { @class = "btn btn-sm btn-default disabled" })
    <span></span>
    @Html.ActionLink(">>", "ListaCompras", new { pagina = Model.TotalPaginas },
                    new { @class = "btn btn-sm btn-default disabled" })
}

<div class="modal fade" data-keyboard="false" data-backdrop="static" id="idModalUpdate" tabindex="-1"></div>
<div class="modal fade" data-keyboard="false" data-backdrop="static" id="idModalElminar" tabindex="-1"></div>
<div class="modal fade" data-keyboard="false" data-backdrop="static" id="idModalEntregada" tabindex="-1"></div>

<script type="text/javascript">
    
    /*$(document).ready(function () {
        $('#Nuevo').click(function () {
            var url = $('#idModalRegistrar').data('url');
            $.get(url, function (data) {
                $("#idModalRegistrar").html(data);
                $("#idModalRegistrar").modal('show');
            });
        });
    });*/



    /*function createModal(url) {
        $.get(url, function (data) {
            $("#idModalUpdate").html(data);
            $("#idModalUpdate").modal('show');
        });

    }

    function createModal(url) {
        $.get(url, function (data) {
            $("#idModalElminar").html(data);
            $("#idModalElminar").modal('show');
        });

    }*/

    function createModal(url) {
        $.get(url, function (data) {
            $("#idModalEntregada").html(data);
            $("#idModalEntregada").modal('show');
        });

    }


</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MerxProject/Views/Compras/ListaDetalleCompra.cshtml
@model MerxProject.Models.PaginadorGenerico<MerxProject.Models.DetalleCompra>

<h2>@ViewBag.title</h2>
@if (ViewBag.compra != null)
{
    if (ViewBag.compra.Estatus < 2)
    {
        <button  class="btn btn-success btn-sm pull-right" data-toggle="modal" id="NuevoH">Nueva Herramienta</button>
        <div class="modal fade" data-keyboard="false" data-backdrop="static" id="idModalRegistrarH" tabindex="-1"
             data-url='@Url.Action("popUpDetalleCompra", "Compras", new { Id = ViewBag.compra.Id, accion = "1", tipo = "H" })'></div>

        <button style="margin-left:15px" class="btn btn-success btn-sm pull-right" data-toggle="modal" id="NuevoMP">Nueva Materia Prima</button>
        <div class="modal fade" data-keyboard="false" data-backdrop="static" id="idModalRegistrarMP" tabindex="-1"
             data-url='@Url.Action("popUpDetalleCompra", "Compras", new { Id = ViewBag.compra.Id, accion = "1", tipo = "MP" })'></div>

        <br />
    }
}
@if (Session["res"] != null)
{
    string color;
    string mensaje = Session["res"].ToString();
    Session.Remove("res");


    if (Session["tipo"] != null)
    {
        color = "#18ce65";
    }
    else
    {
        color = "#cc0001";
    }
    <div class="panel panel-default" id="current-panel">
        <table class="table table-hover">
            <thead>
                <tr style="background-color:@color">
                    <th>
                        <p style="text-align: center">
                            @mensaje
                        </p>
                    </th>
                    <th>
                        <a href="#current-panel" class="close" data-dismiss="alert" aria-label="close" id="hide">
                            &times;
                        </a>
                    </th>
                </tr>
            </thead>
        </table>
    </div>
    Session.Remove("tipo");
}
@if (ViewBag.error != null)
{
    string error = ViewBag.error;
    ViewBag.error = null;
    <div class="panel panel-default" id="current-panel">
        <table class="table table-hover">
            <thead>
                <tr style="background-color: #cc0001">
                    <th>
                        <p style="text-align: center">
                            @error
                        </p>
                    </th>
                    <th>
                        <a href="#current-panel" class="close" data-dismiss="alert" aria-label="close" id="hide">
                            &times;
                        </a>
                    </th>
                </tr>
            </thead>
        </table>
    </div>
}
@if (Model.Resultado != null)
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayName("Tipo")
            </th>
            <th>
                @Html.DisplayName("Artículo")
            </th>
            <th>
                @Html.DisplayName("Cantidad")
            </th>
            <th>
                @Html.DisplayName("Precio Unitario")
            </th>
            <th>
                @Html.DisplayName("Precio Total")
            </th>
        </tr>

        @foreach (var item in Model.Resultado)
        {
            <tr>
                <td>
                    @if (item.Herramienta != null)
                    {
                        @Html.Label("Herramienta")
                    }
                    @if (item.MateriaPrima != null)
                    {
                        @Html.Label("Materia Prima")
                    }
                </td>
                <td>
                    @if (item.Herramienta != null)
                    {
                        @Html.DisplayFor(modelItem => item.Herramienta.Nombre)
                    }
                    @if (item.MateriaPrima != null)
                    {
                        @Html.DisplayFor(modelItem => item.MateriaPrima.Nombre)
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cantidad)
                </td>
                <td>
                    $
                    @if (item.Herramienta != null)
                    {
                        @Html.DisplayFor(modelItem => item.PrecioUnitario, item.Herramienta.Precio)
                    }
                    @if (item.MateriaPrima != null)
                    {
                        @Html.DisplayFor(modelItem => item.PrecioUnitario, item.MateriaPrima.Precio)
                    }
                </td>
                <td>
                    $ @Html.DisplayFor(modelItem => item.PrecioTotal, item.PrecioUnitario * item.Cantidad)
                </td>
                <td>
                    @if (ViewBag.compra.Estatus < 2)
                    {
                        <button class="btn btn-danger btn-sm" id="Elimninar" id="delete_@item.Id"
                                onclick="createModal('@Url.Action("popUpDetalleCompra", "Compras", new { Id = item.Id, accion = "3", idCompra = ViewBag.compra.Id })')">
                            Eliminar
                        </button>
                    }
                </td>
            </tr>
        }
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td><strong>Monto Total</strong></td>
            <td><strong>$ @ViewBag.total</strong></td>
        </tr>
    </table>
}


@*Paginador de registros*@
@if (Model.Resultado.Count() > 0)
{
    <span>
        <strong>@Model.TotalRegistros</strong> registros encontrados
    </span>
    <span>&nbsp;|&nbsp;</span>
    <span>
        Página <strong>@(Model.PaginaActual)</strong> de
        <strong>@Model.TotalPaginas</strong>
    </span>
    <span>&nbsp;|&nbsp;</span>
}
else
{
    <span>No hay resultados para esta búsqueda</span>
    <span>&nbsp;|&nbsp;</span>
}
@if (Model.PaginaActual > 1)
{
    @Html.ActionLink("<<", "ListaDetalleCompra", new { pagina = 1 },
        new { @class = "btn btn-sm btn-default"})
    <span></span>
    @Html.ActionLink("Anterior", "ListaDetalleCompra", new { pagina = Model.PaginaActual - 1 },
        new { @class = "btn btn-sm btn-default" });
}
else
{
    @Html.ActionLink("<<", "ListaDetalleCompra", new { pagina = 1 },
        new { @class = "btn btn-sm btn-default disabled" })
    <span></span>
    @Html.ActionLink("Anterior", "ListaDetalleCompra", new { pagina = 1 },
        new { @class = "btn btn-sm btn-default disabled" })
}
<span></span>
@if (Model.PaginaActual < Model.TotalPaginas)
{
    @Html.ActionLink("Siguiente", "ListaDetalleCompra", new { pagina = Model.PaginaActual + 1 },
                    new { @class = "btn btn-sm btn-default" })
    <span></span>
    @Html.ActionLink(">>", "ListaDetalleCompra", new { pagina = Model.TotalPaginas },
                    new { @class = "btn btn-sm btn-default" })
}
else
{
    @Html.ActionLink("Siguiente", "ListaDetalleCompra", new { pagina = Model.TotalPaginas - 1 },
                    new { @class = "btn btn-sm btn-default disabled" })
    <span></span>
    @Html.ActionLink(">>", "ListaDetalleCompra", new { pagina = Model.TotalPaginas },
                    new { @class = "btn btn-sm btn-default disabled" })
}
<br />
<br />
@Html.ActionLink("<< Lista de Compras", "ListaCompras", "",
                    new { @class = "btn btn-sm btn-default" })



<div class="modal fade" data-keyboard="false" data-backdrop="static" id="idModalUpdate" tabindex="1040"></div>
<div class="modal fade" data-keyboard="false" data-backdrop="static" id="idModalElminar" tabindex="1040"></div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript">
    function createModal(url) {
        $.get(url, function (data) {
            $("#idModalElminar").html(data);
            $("#idModalElminar").modal('show');
        });
    }

    $(document).ready(function () {
        $('#NuevoH').click(function () {
            var url = $('#idModalRegistrarH').data('url');
            $.get(url, function (data) {
                $("#idModalRegistrarH").html(data);
                $("#idModalRegistrarH").modal('show');
            });
        });
    });
    $(document).ready(function () {
        $('#NuevoMP').click(function () {
            var url = $('#idModalRegistrarMP').data('url');
            $.get(url, function (data) {
                $("#idModalRegistrarMP").html(data);
                $("#idModalRegistrarMP").modal('show');
            });
        });
    });
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MerxProject/Views/Compras/_popUpDetalleCompra.cshtml
@model MerxProject.Models.DetalleCompra

@{
    Layout = null;
}
@if (ViewBag.tipo != null)
{
    <tr>
        <td>
            @if (ViewBag.tipo == "H")
            {
                @Html.Label("Herramienta")
            }
            @if (ViewBag.tipo == "MP")
            {
                @Html.Label("Materia Prima")
            }
        </td>
        <td>
            @if (ViewBag.tipo == "H")
            {
                @Html.DropDownListFor(model => model.Herramienta, new SelectList(ViewBag.Articulos, "Id", "Nombre"), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Herramienta, "", new { @class = "text-danger" })
            }
            @if (ViewBag.tipo == "MP")
            {
                @Html.DropDownListFor(model => model.MateriaPrima, new SelectList(ViewBag.Articulos, "Id", "Nombre"), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MateriaPrima, "", new { @class = "text-danger" })
            }
        </td>
        <td>
            @Html.EditorFor(model => model.Cantidad)
            @Html.ValidationMessageFor(model => model.Cantidad, "", new { @class = "text-danger" })
        </td>
        <td>
            @Html.DropDownListFor(model => model.Unidad, EnumHelper.GetSelectList(typeof(MerxProject.Models.Unidades)), new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Unidad, "", new { @class = "text-danger" })
        </td>
        <td>
            $ @Html.DisplayFor(model => model.PrecioUnitario)
            @Html.ValidationMessageFor(model => model.PrecioUnitario, "", new { @class = "text-danger" })
        </td>
        <td>
            $ @Html.DisplayFor(model => model.PrecioTotal)
            @Html.ValidationMessageFor(model => model.PrecioTotal, "", new { @class = "text-danger" })
        </td>
        <td>
            <button type="submit" class="btn btn-primary btn-sm" id="edit_@Model.Id">
                Editar
            </button>
            <button class="btn btn-primary btn-sm" data-toggle="modal" id="Elimninar" id="delete_@Model.Id">
                Eliminar
            </button>

            <input type="hidden" name="accion" value="@ViewBag.Accion" />
        </td>
    </tr>
}